### ISSUE TITLE
Can this module be embedded into Voice SIP to make it a Voice API?

### ISSUE THREAD

**Issue by axchanda** [Nexmo/wsbridge#5]
I had been using the Nexmo VOice API that provides the media as Websocket API and NCCO to control the calls. Can I adapt using this module with FreeSwitch and Nexmo Voice SIP to replicate the Nexmo Voice Websocket API on my side? Immediate replies appreciated. Thanks!

**Comment by csiwek** [comment]
Hello, 
This module only provides the Websocket endpoint that allows to make Outbound WS calls. It does not provide rich NCCO functionalities.

**Comment by axchanda** [comment]
@csiwek I beleieve this can be used to handle incoming calls too ( outbound or inbound calls will be handled by SIP ) and that media from OB or IB calls will be transferred to Websocket URL. Right?

Any idea on how to implement the NCCO functionalites with this on FreeSwitch? Firstly can it be implemented in FreeSwitch?

**Comment by csiwek** [comment]
Wsbridge endpoint can only make *outbound* WS calls. You can easily build a SIP to WS gateway with that. (SIP in any direction)
Implementing  full NCCO in FreeSWITCH is doable but hard. Perhaps very limited functionalities that work for your use case.
