### ISSUE TITLE
How to transfer the call while the user is in Websocket to another extension through DTMF or api calls?

### ISSUE THREAD

**Issue by axchanda** [Nexmo/wsbridge#8]
Hi, The issue is how can i handle off the calls to another extension/ DID number while the call is in websocket connection by capturing the DTMF key presses?

**Comment by csiwek** [comment]
Hi, I don't  quite understand your question. Do you want to initiate transfer from the websocket leg or you want another leg (for example a SIP extension) to initiate the transfer of websocket leg?

**Comment by axchanda** [comment]
@csiwek initiate transfer from the websoket leg to another leg

**Comment by axchanda** [comment]
@csiwek Any updates on this, please? Also pls let me know how I can change/ transfer the call from websocket live streaming to a sip endpoint? Immediate answers would be appreciated!

**Comment by axchanda** [comment]
@csiwek Any updates on this, please? If we want to transfer the call from wsbridge, I need to have another codec or the actual setting by which the call was initated. How to do that?

**Comment by dragos-oancea** [comment]
you probably want to use uuid_transfer:
https://freeswitch.org/confluence/display/FREESWITCH/mod_commands
you don't need "another codec". 
Note WSBridge only does outbound WS.
So you have to have a SIP/RTP call and bridge it through the dialplan to a WS server.

**Comment by axchanda** [comment]
@dragos-oancea  I had already tried upon that. Used uuid_transfer passing the uuid to the WS Server. When needed I tried uuid_transfer by modesl (JS FS ESL api). But the fact is I get a codec SDP error mismatch. When I did a sip trace on the WS was having Linear16 Codec, while phones / softphones weren't accepting the same (they excpet PCMU,, PCMA). Please let me know how to proceed or how to convert coedcs.

**Comment by axchanda** [comment]
@csiwek @dragos-oancea Does this code work for the ;latest FS version 1.10 ?

**Comment by csiwek** [comment]
Wsbridge hasn't been tested with Freeswitch 1.10.  There is no more development happening on this project anymore so please treat it as abandoned.
